import { RemoteType, SeniorityLevel } from "@/store/job-store";

export interface Job {
  id: string;
  title: string;
  company: string;
  companyLogo?: string;
  location: string;
  remoteType: RemoteType;
  postedAt: Date;
  tags: string[];
  relevanceScore: number;
  salary?: {
    min: number;
    max: number;
    currency: "USD" | "EUR" | "GBP";
  };
  seniority: SeniorityLevel;
  description: string;
  saved: boolean;
}

const getRandomDate = (daysBack: number): Date => {
  const now = new Date();
  const randomDays = Math.floor(Math.random() * daysBack);
  const randomHours = Math.floor(Math.random() * 24);
  return new Date(now.getTime() - randomDays * 24 * 60 * 60 * 1000 - randomHours * 60 * 60 * 1000);
};

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "Senior Full Stack Engineer",
    company: "Stripe",
    location: "San Francisco, CA",
    remoteType: "hybrid",
    postedAt: getRandomDate(1),
    tags: ["React", "Node.js", "TypeScript", "PostgreSQL", "AWS"],
    relevanceScore: 95,
    salary: { min: 180000, max: 250000, currency: "USD" },
    seniority: "senior",
    description: "Join our team to build the future of payments infrastructure...",
    saved: false,
  },
  {
    id: "2",
    title: "Staff Software Engineer",
    company: "Figma",
    location: "Worldwide",
    remoteType: "worldwide",
    postedAt: getRandomDate(2),
    tags: ["Python", "Django", "React", "GraphQL", "Kubernetes"],
    relevanceScore: 88,
    salary: { min: 200000, max: 300000, currency: "USD" },
    seniority: "lead",
    description: "Help us scale our design collaboration platform...",
    saved: true,
  },
  {
    id: "3",
    title: "Frontend Developer",
    company: "Notion",
    location: "New York, NY",
    remoteType: "hybrid",
    postedAt: getRandomDate(3),
    tags: ["React", "TypeScript", "CSS", "WebGL", "Next.js"],
    relevanceScore: 82,
    salary: { min: 140000, max: 180000, currency: "USD" },
    seniority: "mid",
    description: "Build beautiful and performant user interfaces...",
    saved: false,
  },
  {
    id: "4",
    title: "Backend Engineer",
    company: "Linear",
    location: "Europe / US Timezones",
    remoteType: "regional",
    postedAt: getRandomDate(1),
    tags: ["Go", "PostgreSQL", "Redis", "GraphQL", "Docker"],
    relevanceScore: 79,
    salary: { min: 150000, max: 200000, currency: "USD" },
    seniority: "mid",
    description: "Architect and build high-performance systems...",
    saved: false,
  },
  {
    id: "5",
    title: "Principal Engineer",
    company: "Vercel",
    location: "Worldwide",
    remoteType: "worldwide",
    postedAt: getRandomDate(5),
    tags: ["TypeScript", "React", "Node.js", "Edge Computing", "System Design"],
    relevanceScore: 91,
    salary: { min: 250000, max: 350000, currency: "USD" },
    seniority: "lead",
    description: "Lead technical direction for our cloud platform...",
    saved: false,
  },
  {
    id: "6",
    title: "Junior Software Developer",
    company: "Shopify",
    location: "Toronto, Canada",
    remoteType: "onsite",
    postedAt: getRandomDate(7),
    tags: ["Ruby", "Rails", "React", "MySQL", "Sidekiq"],
    relevanceScore: 65,
    salary: { min: 80000, max: 110000, currency: "USD" },
    seniority: "entry",
    description: "Start your career building e-commerce solutions...",
    saved: false,
  },
  {
    id: "7",
    title: "Senior Platform Engineer",
    company: "Datadog",
    location: "Boston, MA",
    remoteType: "hybrid",
    postedAt: getRandomDate(4),
    tags: ["Go", "Kubernetes", "AWS", "Prometheus", "Terraform"],
    relevanceScore: 85,
    salary: { min: 175000, max: 230000, currency: "USD" },
    seniority: "senior",
    description: "Build and scale our monitoring infrastructure...",
    saved: true,
  },
  {
    id: "8",
    title: "Full Stack Developer",
    company: "Deel",
    location: "Worldwide",
    remoteType: "worldwide",
    postedAt: getRandomDate(2),
    tags: ["Next.js", "TypeScript", "Prisma", "TailwindCSS", "Vercel"],
    relevanceScore: 78,
    salary: { min: 130000, max: 170000, currency: "USD" },
    seniority: "mid",
    description: "Help us build the future of global hiring...",
    saved: false,
  },
  {
    id: "9",
    title: "Engineering Manager",
    company: "GitLab",
    location: "Americas Timezones",
    remoteType: "regional",
    postedAt: getRandomDate(6),
    tags: ["Ruby", "Go", "Kubernetes", "Leadership", "Agile"],
    relevanceScore: 72,
    salary: { min: 200000, max: 280000, currency: "USD" },
    seniority: "lead",
    description: "Lead a distributed engineering team...",
    saved: false,
  },
  {
    id: "10",
    title: "DevOps Engineer",
    company: "HashiCorp",
    location: "Worldwide",
    remoteType: "worldwide",
    postedAt: getRandomDate(8),
    tags: ["Terraform", "Vault", "Consul", "AWS", "GCP"],
    relevanceScore: 83,
    salary: { min: 160000, max: 210000, currency: "USD" },
    seniority: "senior",
    description: "Build infrastructure-as-code solutions...",
    saved: false,
  },
  {
    id: "11",
    title: "Software Engineer II",
    company: "Spotify",
    location: "Stockholm, Sweden",
    remoteType: "onsite",
    postedAt: getRandomDate(3),
    tags: ["Java", "Kafka", "Python", "TensorFlow", "Cassandra"],
    relevanceScore: 70,
    salary: { min: 120000, max: 160000, currency: "EUR" },
    seniority: "mid",
    description: "Build recommendation systems for millions of users...",
    saved: false,
  },
  {
    id: "12",
    title: "Senior Frontend Engineer",
    company: "Framer",
    location: "Amsterdam, Netherlands",
    remoteType: "hybrid",
    postedAt: getRandomDate(1),
    tags: ["React", "TypeScript", "Three.js", "Framer Motion", "WebGL"],
    relevanceScore: 86,
    salary: { min: 140000, max: 180000, currency: "EUR" },
    seniority: "senior",
    description: "Create powerful design and prototyping tools...",
    saved: false,
  },
  {
    id: "13",
    title: "Platform Architect",
    company: "Snowflake",
    location: "San Mateo, CA",
    remoteType: "hybrid",
    postedAt: getRandomDate(5),
    tags: ["Scala", "Spark", "Kafka", "Delta Lake", "dbt"],
    relevanceScore: 75,
    salary: { min: 220000, max: 300000, currency: "USD" },
    seniority: "lead",
    description: "Architect next-gen data warehouse solutions...",
    saved: false,
  },
  {
    id: "14",
    title: "Junior Web Developer",
    company: "Webflow",
    location: "Worldwide",
    remoteType: "worldwide",
    postedAt: getRandomDate(2),
    tags: ["JavaScript", "React", "GraphQL", "Node.js", "MongoDB"],
    relevanceScore: 68,
    salary: { min: 90000, max: 120000, currency: "USD" },
    seniority: "entry",
    description: "Help build the future of no-code web development...",
    saved: false,
  },
  {
    id: "15",
    title: "Senior Data Engineer",
    company: "Databricks",
    location: "Seattle, WA",
    remoteType: "hybrid",
    postedAt: getRandomDate(4),
    tags: ["Python", "Spark", "Delta Lake", "MLflow", "Apache Airflow"],
    relevanceScore: 87,
    salary: { min: 170000, max: 220000, currency: "USD" },
    seniority: "senior",
    description: "Build scalable data pipelines and ML platforms...",
    saved: false,
  },
  {
    id: "16",
    title: "Technical Lead - Payments",
    company: "Adyen",
    location: "Amsterdam, Netherlands",
    remoteType: "onsite",
    postedAt: getRandomDate(6),
    tags: ["Java", "Spring Boot", "PostgreSQL", "Kafka", "Microservices"],
    relevanceScore: 74,
    salary: { min: 130000, max: 170000, currency: "EUR" },
    seniority: "lead",
    description: "Lead our global payment processing systems...",
    saved: false,
  },
  {
    id: "17",
    title: "Full Stack Developer",
    company: "Coda",
    location: "US / Europe Timezones",
    remoteType: "regional",
    postedAt: getRandomDate(3),
    tags: ["React", "Node.js", "MongoDB", "Electron", "Canvas API"],
    relevanceScore: 71,
    salary: { min: 145000, max: 190000, currency: "USD" },
    seniority: "mid",
    description: "Build the next generation of collaborative documents...",
    saved: false,
  },
  {
    id: "18",
    title: "Senior Infrastructure Engineer",
    company: "Cloudflare",
    location: "London, UK",
    remoteType: "hybrid",
    postedAt: getRandomDate(7),
    tags: ["Rust", "C++", "Linux", "Networking", "BPF"],
    relevanceScore: 66,
    salary: { min: 150000, max: 200000, currency: "GBP" },
    seniority: "senior",
    description: "Build and optimize edge computing infrastructure...",
    saved: false,
  },
  {
    id: "19",
    title: "Staff Product Engineer",
    company: "Loom",
    location: "San Francisco, CA",
    remoteType: "hybrid",
    postedAt: getRandomDate(1),
    tags: ["React", "TypeScript", "WebRTC", "FFmpeg", "Electron"],
    relevanceScore: 89,
    salary: { min: 210000, max: 280000, currency: "USD" },
    seniority: "lead",
    description: "Build industry-leading video messaging tools...",
    saved: false,
  },
  {
    id: "20",
    title: "Mid-Level Backend Engineer",
    company: "Monzo",
    location: "London, UK",
    remoteType: "hybrid",
    postedAt: getRandomDate(5),
    tags: ["Go", "PostgreSQL", "Kubernetes", "gRPC", "Event Sourcing"],
    relevanceScore: 77,
    salary: { min: 100000, max: 140000, currency: "GBP" },
    seniority: "mid",
    description: "Reinvent banking with modern technology...",
    saved: false,
  },
  {
    id: "21",
    title: "Senior React Developer",
    company: "Miro",
    location: "Worldwide",
    remoteType: "worldwide",
    postedAt: getRandomDate(2),
    tags: ["React", "TypeScript", "Canvas API", "WebSocket", "Redux"],
    relevanceScore: 84,
    salary: { min: 155000, max: 195000, currency: "USD" },
    seniority: "senior",
    description: "Build collaborative whiteboard experiences...",
    saved: false,
  },
  {
    id: "22",
    title: "Systems Engineer",
    company: "Canonical",
    location: "Worldwide",
    remoteType: "worldwide",
    postedAt: getRandomDate(10),
    tags: ["Python", "Go", "Linux", "Ansible", "Kubernetes"],
    relevanceScore: 62,
    salary: { min: 110000, max: 150000, currency: "USD" },
    seniority: "mid",
    description: "Build and maintain Ubuntu infrastructure...",
    saved: false,
  },
  {
    id: "23",
    title: "Lead Solutions Architect",
    company: "MongoDB",
    location: "New York, NY",
    remoteType: "onsite",
    postedAt: getRandomDate(8),
    tags: ["MongoDB", "Node.js", "AWS", "Architecture", "Consulting"],
    relevanceScore: 73,
    salary: { min: 190000, max: 260000, currency: "USD" },
    seniority: "lead",
    description: "Design solutions for enterprise customers...",
    saved: false,
  },
  {
    id: "24",
    title: "ML Infrastructure Engineer",
    company: "Anthropic",
    location: "San Francisco, CA",
    remoteType: "onsite",
    postedAt: getRandomDate(4),
    tags: ["Python", "PyTorch", "Kubernetes", "ML Infrastructure", "CUDA"],
    relevanceScore: 92,
    salary: { min: 250000, max: 400000, currency: "USD" },
    seniority: "senior",
    description: "Build infrastructure for frontier AI systems...",
    saved: false,
  },
];

export const industries = [
  "Technology",
  "Finance",
  "Healthcare",
  "E-commerce",
  "SaaS",
  "Education",
  "Media & Entertainment",
  "Manufacturing",
  "Real Estate",
  "Transportation",
  "Energy",
  "Consulting",
];

export const techSkills = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Go",
  "Rust",
  "Java",
  "Kotlin",
  "Ruby",
  "PHP",
  "C#",
  "Swift",
  "React",
  "Vue.js",
  "Angular",
  "Next.js",
  "Svelte",
  "Node.js",
  "Django",
  "FastAPI",
  "Spring Boot",
  "Express.js",
  "GraphQL",
  "REST API",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "Elasticsearch",
  "Cassandra",
  "DynamoDB",
  "AWS",
  "Google Cloud",
  "Azure",
  "Kubernetes",
  "Docker",
  "Terraform",
  "CI/CD",
  "Linux",
  "Git",
  "Agile",
  "Machine Learning",
  "AI",
  "Data Science",
  "Blockchain",
  "WebGL",
  "Three.js",
  "Electron",
];
